"""empty message

Revision ID: 32c5732b15f6
Revises: f083361b5e82
Create Date: 2022-03-21 22:52:08.051042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c5732b15f6'
down_revision = 'f083361b5e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.drop_table('artist_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_venues',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='artist_venues_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='artist_venues_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id', name='artist_venues_pkey')
    )
    op.drop_table('venue_genres')
    # ### end Alembic commands ###
