"""empty message

Revision ID: f083361b5e82
Revises: a0e502a8deb8
Create Date: 2022-03-21 22:42:13.261887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f083361b5e82'
down_revision = 'a0e502a8deb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('artist_venues',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.add_column('artists', sa.Column('website', sa.String(length=500), nullable=True))
    op.drop_constraint('artists_genre_id_fkey', 'artists', type_='foreignkey')
    op.drop_column('artists', 'genre_id')
    op.add_column('venues', sa.Column('website', sa.String(length=500), nullable=True))
    op.drop_constraint('venues_genre_id_fkey', 'venues', type_='foreignkey')
    op.drop_column('venues', 'genre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('venues_genre_id_fkey', 'venues', 'genres', ['genre_id'], ['id'])
    op.drop_column('venues', 'website')
    op.add_column('artists', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artists_genre_id_fkey', 'artists', 'genres', ['genre_id'], ['id'])
    op.drop_column('artists', 'website')
    op.drop_table('artist_venues')
    op.drop_table('artist_genres')
    # ### end Alembic commands ###
